### ISSUE TITLE
index.js:1 Error: Setting up fake worker failed: "Cannot load script at: https://gitcdn.xyz/repo/mozilla/pdf.js/gh-pages/build/pdf.worker.js"

### ISSUE THREAD

**Issue by sl1mpshady** [abidhkm/react-pdf-preview#1]
![image](https://user-images.githubusercontent.com/11581869/75781375-7b0a0600-5d76-11ea-9d21-edccd8d99e95.png)

**Comment by sl1mpshady** [comment]
Can't push a new branch @abidhkm . I have a possible fix pull request

**Comment by abidhkm** [comment]
added you as collaborator.

**Comment by abidhkm** [comment]
fixed this in latest version 1.0.4
